// Generated by scripts/extract-seed-summer-wanter.mjs from Summer_Wanter_Froen_Antwerten.md — do not hand-edit.
import type { SeedTopic } from "./seed-sproochen";

export const seedTopics: SeedTopic[] = [
  {
    "id": "summer-wanter",
    "name": "Summer / Wanter",
    "cards": [
      [
        "Vu wou kommt Dir?",
        "Откуда Вы родом?",
        "Ech kommen aus Russland",
        "Я из России"
      ],
      [
        "Wéi ass de Wanter an Ärem Land?",
        "Какая зима в Вашей родной стране?",
        "An mengem Land ass de Wanter kal a laang",
        "В моей стране зима холодная и долгая"
      ],
      [
        "Schneit et do vill?",
        "Там много снега?",
        "Jo, do schneit et vill",
        "Да, там много снега"
      ],
      [
        "Reent et do och?",
        "Там много дождя?",
        "Jo, mee et reent an de verschiddene Regiounen ënnerschiddlech",
        "Да, но в разных регионах по-разному"
      ],
      [
        "Wéi fannt Dir de Wanter hei zu Lëtzebuerg?",
        "Как Вы находите зиму в Люксембурге?",
        "De Wanter zu Lëtzebuerg ass mëll a mëll waarm.",
        "Зима в Люксембурге мягкая и довольно тёплая."
      ],
      [
        "Wat gefält Iech besser de Wanter hei oder an Ärem Land?",
        "Что Вам больше нравится: зима здесь или в вашей стране?",
        "Ech hunn de Wanter zu Lëtzebuerg léiwer, well en méi waarm ass.",
        "Я предпочитаю зиму в Люксембурге, потому что она теплее."
      ],
      [
        "Firwat hutt Dir de Wanter an Ärem Land léiwer?",
        "Почему Вы предпочитаете зиму в Вашей стране?",
        "Ech hunn de Wanter a mengem Land léiwer, well ech do Schi fuere kann.",
        "Я предпочитаю зиму в своей стране, потому что могу кататься на лыжах."
      ],
      [
        "Wat maacht Dir an Ärer Fräizäit am Wanter hei zu Lëtzebuerg?",
        "Что Вы делаете зимой в Ваше свободное время здесь в Люксембурге?",
        "Ech ginn op de Chrëschtmaart, ech schaffe, an ech ginn an d'Vakanz",
        "Я хожу на рождественский рынок, работаю и езжу в отпуск"
      ],
      [
        "Wat sinn déi typesch Fräizäitaktivitéiten am Wanter an Ärem Land?",
        "Какие есть типичные зимние развлечения в Вашей стране?",
        "Am Wanter zu Moskau maache d'Leit Wantersport",
        "Зимой в Москве люди занимаются зимними видами спорта"
      ],
      [
        "Maacht Dir Wantersportaarten?",
        "Вы занимаетесь зимними видами спорта?",
        "Jo, ech fuere Schi.",
        "Да, я катаюсь на лыжах."
      ],
      [
        "Fuert Dir an de Wantersport?",
        "Вы ездите на зимние каникулы?",
        "Jo, ech fuere mat menge Frënn Schi.",
        "Да, я езжу кататься на лыжах с друзьями."
      ],
      [
        "Wat gefält Iech besonnesch um Wanter?",
        "Что Вам особенно нравится в зиме?",
        "Ech hunn Schnéi gär",
        "Мне нравится снег"
      ],
      [
        "Wat gefält Iech guer net um Wanter?",
        "Что Вам совсем не нравится в зиме?",
        "Et ass kal",
        "Холодно"
      ],
      [
        "Waart Dir de leschte Wanter hei zu Lëtzebuerg?",
        "Вы были последней зимой в Люксембурге?",
        "Jo, ech war de leschte Wanter zu Lëtzebuerg.",
        "Да, я была прошлой зимой в Люксембурге."
      ],
      [
        "Wéi hutt Dir dee Wanter fonnt?",
        "Как Вам понравилась та зима?",
        "De Wanter war kal an donkel",
        "Зима была холодная и тёмная"
      ],
      [
        "Wat fir eng Joreszäit hutt Dir am léifsten?",
        "Какое Ваше любимое время года?",
        "Am léifsten hunn ech de Summer",
        "Больше всего я люблю лето"
      ],
      [
        "Firwat hutt Dir dës Joreszäit am léifsten?",
        "Почему Вам нравится именно это время года?",
        "Well et sonneg an waarm ass",
        "Потому что солнечно и тепло"
      ],
      [
        "Wéi eng Joreszäit gefält Iech am mannsten?",
        "Какое время года Вам нравится меньше всего?",
        "Ech hunn de Wanter net gär",
        "Я не люблю зиму"
      ],
      [
        "Firwat hutt Dir dës Joreszäit guer net gär?",
        "Почему Вам совсем не нравится это время года?",
        "Well et kal an naass ass",
        "Потому что холодно и сыро"
      ],
      [
        "Wéini waart Dir fir d'lescht an der Vakanz?",
        "Когда Вы были в последний раз в отпуске?",
        "Ech war am Hierscht an der Vakanz.",
        "Я была в отпуске осенью."
      ],
      [
        "A wéi enger Joreszäit war dat?",
        "В какое время года это было?",
        "Dat war am Hierscht.",
        "Это было осенью."
      ],
      [
        "A wéi engem Mount war dat?",
        "В каком месяце это было?",
        "Dat war am September.",
        "Это было в сентябре."
      ],
      [
        "Wéi war d'Wieder an Ärer Vakanz?",
        "Какая была погода на каникулах?",
        "D'Wieder war waarm.",
        "Погода была тёплой."
      ],
      [
        "Wéi ass d'Wiedersituatioun haut zu Lëtzebuerg?",
        "Какая сегодня погода в Люксембурге?",
        "Haut ass et sonneg",
        "Сегодня солнечно"
      ],
      [
        "Wéi ass d'Wieder haut an Ärem Heemechtsland?",
        "Какая сегодня погода в Вашей родной стране?",
        "Ech weess et net",
        "Я не знаю"
      ],
      [
        "Wéi ass d'Wieder haut an Ärer Heemechtsstad?",
        "Какая сегодня погода в Вашем родном городе?",
        "Ech weess et net",
        "Я не знаю"
      ],
      [
        "Fannt Dir d'Wieder zu Lëtzebuerg am Generelle besser wéi an Ärem Land oder méi schlecht?",
        "В целом, Вы считаете погоду в Люксембурге лучше или хуже, чем в Вашей стране?",
        "Ech fannen d'Wieder zu Lëtzebuerg besser wéi a Russland, well et hei méi waarm ass.",
        "Я считаю погоду в Люксембурге лучше, чем в России, потому что здесь теплее."
      ],
      [
        "Wat gefält Iech um Wieder zu Lëtzebuerg a wat net?",
        "Что Вам нравится в погоде в Люксембурге, а что нет?",
        "Mir gefält, datt et hei waarm ass, mee et reent vill an et ass oft bedeckt.",
        "Мне нравится, что здесь тепло, хотя много дождей и облачности."
      ],
      [
        "Wéi eng Kleeder dot Dir un, wann et reent?",
        "Какую одежду Вы надеваете, когда идёт дождь?",
        "Ech huele e Prabbel mat",
        "Я беру с собой зонт"
      ],
      [
        "Wat dot Dir un, wann et schneit a méi kal ass?",
        "Что Вы надеваете, когда идёт снег и холодно?",
        "Ech doen eppes waarmes un",
        "Я надеваю что-то тёплое"
      ],
      [
        "Wéi informéiert Dir Iech iwwer d'Wieder?",
        "Как Вы осведомляетесь о погоде?",
        "Ech kucken d'Wieder um Internet",
        "Я смотрю погоду в интернете"
      ],
      [
        "Wéi oft informéiert Dir Iech iwwer d'Wieder?",
        "Как часто Вы проверяете погоду?",
        "Ech maachen dat seelen",
        "Я делаю это редко"
      ],
      [
        "Kuckt Dir d'Wiederprevisiounen online?",
        "Вы смотрите прогноз погоды в интернете?",
        "Jo, ech kucken déi online",
        "Да, я смотрю их онлайн"
      ],
      [
        "Trëfft d'Meteo zou oder waart Dir schonn eng Kéier enttäuscht ginn?",
        "Прогноз погоды соответствует действительности или Вы уже были когда-то разочарованы?",
        "Se trëffen zou",
        "Обычно совпадает"
      ],
      [
        "Sinn d'Wiederprevisioune richteg oder heiansdo och falsch?",
        "Прогноз погоды обычно правильный или иногда неверный?",
        "Jo, se si richteg",
        "Да, они правильные"
      ],
      [
        "Firwat informéiert Dir Iech iwwer d'Meteo?",
        "Зачем Вы проверяете прогноз погоды?",
        "Fir mech richteg unzedoen",
        "Чтобы правильно одеваться"
      ],
      [
        "Wéi fannt Dir de Summer zu Lëtzebuerg?",
        "Как Вам лето в Люксембурге?",
        "De Summer zu Lëtzebuerg ass wonnerbar an sonneg",
        "Лето в Люксембурге замечательное и солнечное"
      ],
      [
        "Gefält Iech besser de Summer hei zu Lëtzebuerg oder an Ärem Land?",
        "Вы предпочитаете лето в Люксембурге или в Вашей родной стране?",
        "Mir gefält de Summer iwweral",
        "Мне нравится лето везде"
      ],
      [
        "Wéi ass d'Wieder am Summer an Ärem Land?",
        "Какая погода летом в Вашей стране?",
        "De Summer zu Moskau ass och wonnerbar an sonneg",
        "Лето в Москве тоже замечательное и солнечное"
      ],
      [
        "Wéi kann een d'Summervakanz an Ärem Land verbréngen?",
        "Как можно провести летние каникулы в Вашей стране?",
        "Et kann een un d'Mier goen an der Summervakanz",
        "Можно поехать на море на летние каникулы"
      ],
      [
        "Wéi verbréngt Dir normalerweis de Summer?",
        "Как Вы обычно проводите лето?",
        "Ech schaffen, mee ech treffen meng Frënn a verschiddene Länner",
        "Я работаю, но встречаюсь с друзьями в разных странах"
      ],
      [
        "Fuert Dir am Summer dacks fort?",
        "Вы летом часто уезжаете?",
        "Jo, ech fueren sechsmol de Summer fort",
        "Да, я уезжаю шесть раз за лето"
      ],
      [
        "Hutt Dir scho Pläng fir den nächste Summer?",
        "У Вас уже есть планы на следующее лето?",
        "Ech hu nach keng Pläng fir den nächste Summer.",
        "У меня ещё нет планов на следующее лето."
      ],
      [
        "Wéi vill Zäit verbréngt Dir am Summer dobaussen?",
        "Сколько времени Вы проводите летом на улице?",
        "Ech probéieren esou vill Zäit wéi méiglech dobaussen ze verbréngen, mee ech schaffen vun doheem",
        "Я стараюсь проводить как можно больше времени на улице, но работаю из дома"
      ],
      [
        "Wéi vill Stonnen den Dag verbréngt Dir am Summer dobaussen?",
        "Сколько часов в день Вы проводите летом на улице?",
        "Ech probéieren zwou Stonnen den Dag dobaussen ze sinn",
        "Я стараюсь быть на улице два часа в день"
      ],
      [
        "Wat kënnt Dir am Summer hei zu Lëtzebuerg ënnerhuelen?",
        "Чем Вы можете заняться летом здесь в Люксембурге?",
        "Am Summer kann een zu Lëtzebuerg wanderen oder mam Vëlo fueren",
        "Летом в Люксембурге можно ходить в походы или кататься на велосипеде"
      ],
      [
        "Hutt Dir e Gaart oder eng Terrass?",
        "У Вас есть сад или терраса?",
        "Jo, ech hunn eng Terrass",
        "Да, у меня есть терраса"
      ],
      [
        "Wéi vill Zäit verbréngt Dir do?",
        "Сколько времени Вы там проводите?",
        "Ech verbréngen ongeféier zwou Stonnen den Dag op menger Terrass",
        "Я провожу примерно два часа в день на своей террасе"
      ],
      [
        "Wat maacht Dir do?",
        "Что Вы там делаете?",
        "Ech genéissen d'Fräizäit, drénken Téi oder liesen e Buch",
        "Я наслаждаюсь свободным временем, пью чай или читаю книгу"
      ]
    ]
  }
];
