// Generated by scripts/extract-seed.mjs from sproochen-cards.html — do not hand-edit.
export type SeedCard = [questionLu: string, questionRu: string, answerLu: string, answerRu: string];
export type SeedTopic = { id: string; name: string; cards: SeedCard[] };

export const seedTopics: SeedTopic[] = [
  {
    "id": "sproochen",
    "name": "Sproochen",
    "cards": [
      [
        "Wat fir Sprooche schwätzt Dir?",
        "На каких языках Вы говорите?",
        "Ech schwätze Russesch, Englesch a Lëtzebuergesch.",
        "Я говорю по-русски, по-английски и по-люксембургски."
      ],
      [
        "Wéi vill Sprooche schwätzt Dir?",
        "На скольких языках Вы говорите?",
        "Ech schwätzen dräi Sproochen.",
        "Я говорю на трёх языках."
      ],
      [
        "Wat ass Är Mammesprooch?",
        "Какой у Вас родной язык?",
        "Meng Mammesprooch ass Russesch.",
        "Мой родной язык — русский."
      ],
      [
        "Zanter wéini léiert Dir Lëtzebuergesch?",
        "С каких пор Вы учите люксембургский?",
        "Ech léieren zanter sechs Méint Lëtzebuergesch.",
        "Я учу люксембургский шесть месяцев."
      ],
      [
        "Wéi léiert Dir Lëtzebuergesch?",
        "Как Вы учите люксембургский?",
        "Ech léieren Lëtzebuergesch mat enger Prof online op Educate Me.",
        "Я учу люксембургский с преподавателем онлайн на Educate Me."
      ],
      [
        "Wou léiert Dir Lëtzebuergesch?",
        "Где Вы учите люксембургский?",
        "Ech léieren Lëtzebuergesch online, doheem.",
        "Я учу люксембургский онлайн, дома."
      ],
      [
        "Firwat léiert Dir Lëtzebuergesch?",
        "Почему Вы учите люксембургский?",
        "Ech wunnen a schaffen zu Lëtzebuerg, dofir léieren ech d'Sprooch.",
        "Я живу и работаю в Люксембурге, поэтому учу язык."
      ],
      [
        "Wat ass Är Motivatioun, fir Lëtzebuergesch ze léieren?",
        "Какая у Вас мотивация учить люксембургский?",
        "Ech wëll mech zu Lëtzebuerg integréieren.",
        "Я хочу интегрироваться в Люксембурге."
      ],
      [
        "Wéi oft hutt Dir Lëtzebuergeschcours?",
        "Как часто у Вас курсы люксембургского?",
        "Ech hu Lëtzebuergeschcours zweemol d'Woch.",
        "У меня курсы люксембургского дважды в неделю."
      ],
      [
        "Wéini hutt Dir normalerweis Lëtzebuergeschcours?",
        "В какие дни у Вас курсы люксембургского?",
        "Dat ass méindes an donneschdes.",
        "По понедельникам и четвергам."
      ],
      [
        "Um wéi vill Auer ass Äre Lëtzebuergeschcours?",
        "В котором часу Ваши курсы люксембургского?",
        "Dat ass um eng Auer nomëttes.",
        "В час дня."
      ],
      [
        "Wéi laang dauert eng Lëtzebuergeschstonn?",
        "Сколько длится один урок люксембургского?",
        "E Cours dauert eng Stonn.",
        "Один урок длится один час."
      ],
      [
        "Um wéi vill Auer fänkt Äre Lëtzebuergeschcours un?",
        "Во сколько начинаются Ваши курсы люксембургского?",
        "En fänkt um eng Auer un.",
        "Они начинаются в час дня."
      ],
      [
        "Um wéi vill Auer hält Äre Lëtzebuergeschcours op?",
        "Во сколько заканчиваются Ваши курсы люксембургского?",
        "En hält um zwou Auer op.",
        "Они заканчиваются в два часа."
      ],
      [
        "Wat maacht Dir am Cours?",
        "Что Вы делаете на курсах?",
        "Mir léiere Grammatik an trainéieren d'Theeme fir den Examen.",
        "Мы учим грамматику и тренируем темы для экзамена."
      ],
      [
        "Liest Dir Texter aus dem Buch?",
        "Вы читаете тексты из книги?",
        "Jo, heiansdo liese mir Texter.",
        "Да, иногда мы читаем тексты."
      ],
      [
        "Schwätzt Dir vill am Cours?",
        "Вы много говорите на уроке?",
        "Jo, mir probéieren ze schwätzen.",
        "Да, мы стараемся говорить."
      ],
      [
        "Lauschtert Dir Opnamen?",
        "Вы слушаете записи?",
        "Jo, mir probéieren ze lauschteren.",
        "Да, мы стараемся слушать."
      ],
      [
        "Wat fir e Léierbuch benotzt Dir am Cours?",
        "Какой учебник Вы используете на курсах?",
        "Dat sinn zwee Bicher vum INL: \"Schwätzt Dir Lëtzebuergesch A1\" an \"A2\".",
        "Это две книги от INL: «Schwätzt Dir Lëtzebuergesch A1» и «A2»."
      ],
      [
        "Wéi gefält Iech dat Léierbuch?",
        "Как Вам этот учебник?",
        "D'Buch ass gutt.",
        "Учебник хороший."
      ],
      [
        "Wéi heescht Äre Prof?",
        "Как зовут Вашего преподавателя?",
        "Meng Proff heescht Stella.",
        "Мою преподавательницу зовут Стелла."
      ],
      [
        "Wéi fannt Dir Äre Prof?",
        "Как Вам Ваш преподаватель?",
        "Si ass gutt.",
        "Она хорошая."
      ],
      [
        "Kritt Dir Hausaufgaben?",
        "Вам дают домашнее задание?",
        "Jo, ech kréien Hausaufgaben.",
        "Да, мне задают домашнее задание."
      ],
      [
        "Wéi eng Hausaufgabe kritt Dir meeschtens?",
        "Какое домашнее задание Вам чаще всего дают?",
        "Ech kréien meeschtens grammatesch Hausaufgaben.",
        "Чаще всего я получаю грамматические задания."
      ],
      [
        "Wéini hutt Dir Zäit, fir d'Hausaufgaben ze maachen?",
        "Когда у Вас есть время, чтобы выполнять домашнее задание?",
        "Ech maachen meng Hausaufgaben owes.",
        "Я делаю домашнее задание по вечерам."
      ],
      [
        "Wat motivéiert Iech, fir eng Sprooch ze léieren?",
        "Что Вас мотивирует изучать язык?",
        "Ech léiere gär eng Sprooch, fir mat anere Leit ze schwätzen.",
        "Мне нравится учить язык, чтобы говорить с другими людьми."
      ],
      [
        "Wat hëlleft Iech, fir eng Sprooch ze léieren?",
        "Что Вам помогает выучить язык?",
        "D'Praxis an d'Kaarten hëllefe mir, fir eng Sprooch ze léieren.",
        "Практика и карточки помогают мне учить язык."
      ],
      [
        "Hutt Dir vläicht eng speziell Method fir ze léieren?",
        "Может быть, у Вас есть особый способ?",
        "Jo, ech liesen vill Texter.",
        "Да, я читаю много текстов."
      ],
      [
        "Benotzt Dir eng App, fir d'Sprooch ze léieren?",
        "Вы используете приложение для изучения?",
        "Jo, ech benotzen de Quizlet mat Kaarten an de Claude.",
        "Да, я использую Quizlet с карточками и Claude."
      ],
      [
        "Wat ass den Avantage vun sou enger App?",
        "В чём преимущество таких приложений?",
        "De Claude hëlleft mir, Texter ze iwwersetzen a Sätz ze bilden.",
        "Claude помогает мне переводить тексты и составлять предложения."
      ],
      [
        "Firwat ass dat praktesch?",
        "Почему это удобно?",
        "Et ass praktesch, well et mir hëlleft, Texter ze iwwersetzen a Sätz ze bilden.",
        "Это удобно, потому что помогает переводить тексты и составлять предложения."
      ],
      [
        "Wéi oft benotzt Dir déi App?",
        "Как часто Вы используете это приложение?",
        "Ech benotzen d'App all Cours.",
        "Я использую приложение каждый урок."
      ],
      [
        "Wou schwätzt Dir Lëtzebuergesch?",
        "Где Вы разговариваете на люксембургском?",
        "Ech schwätze Lëtzebuergesch am Cours an am Geschäft.",
        "Я говорю на люксембургском на курсе и в магазине."
      ],
      [
        "Kuckt Dir d'Tëlee op Lëtzebuergesch?",
        "Вы смотрите телевизор на люксембургском?",
        "Nee, ech kucke keng Tëlee op Lëtzebuergesch.",
        "Нет, я не смотрю телевизор на люксембургском."
      ],
      [
        "Lauschtert Dir de Radio op Lëtzebuergesch?",
        "Вы слушаете радио на люксембургском?",
        "Nee, ech lauschtere kee Radio op Lëtzebuergesch.",
        "Нет, я не слушаю радио на люксембургском."
      ],
      [
        "Liest Dir Bicher op Lëtzebuergesch?",
        "Вы читаете книги на люксембургском?",
        "Nee, ech liese keng Bicher op Lëtzebuergesch.",
        "Нет, я не читаю книги на люксембургском."
      ],
      [
        "Wéi ass et mat den Noriichten?",
        "А как насчёт новостей?",
        "Nee, ech liesen d'Noriichten net op Lëtzebuergesch.",
        "Нет, я не читаю новости на люксембургском."
      ],
      [
        "Liest Dir d'Noriichten op Lëtzebuergesch?",
        "Вы читаете новости на люксембургском?",
        "Nee, ech liese keng Noriichten op Lëtzebuergesch.",
        "Нет, я не читаю новости на люксембургском."
      ],
      [
        "Ass Lëtzebuergesch schwéier?",
        "Люксембургский — сложный?",
        "Jo, Lëtzebuergesch ass eng schwéier Sprooch fir mech.",
        "Да, люксембургский — сложный язык для меня."
      ],
      [
        "Wat ass schwéier am Lëtzebuergeschen?",
        "Что сложного в люксембургском?",
        "D'Grammatik ass schwéier am Lëtzebuergeschen.",
        "В люксембургском сложная грамматика."
      ],
      [
        "Ass Lëtzebuergesch fir Iech méi schwéier oder méi einfach wéi zum Beispill Englesch?",
        "Люксембургский для Вас сложнее или проще, чем, например, английский?",
        "Lëtzebuergesch ass fir mech méi schwéier wéi Englesch.",
        "Люксембургский для меня сложнее английского."
      ],
      [
        "Ginn et nach aner Sproochen, déi Dir léiere wëllt?",
        "Какие другие языки Вы хотите изучать?",
        "Jo, ech wëll nach Franséisch léieren.",
        "Да, я хочу ещё учить французский."
      ],
      [
        "Sidd Dir motivéiert, fir nach eng aner Sprooch ze léieren?",
        "Вы хотите выучить ещё один язык?",
        "Jo, ech sinn motivéiert, fir nach Franséisch ze léieren.",
        "Да, я хочу выучить ещё французский."
      ],
      [
        "Firwat wëllt Dir Franséisch léieren?",
        "Почему Вы хотели бы выучить французский?",
        "Ech wëll Franséisch léieren, fir mat de Leit zu Lëtzebuerg an a Frankräich ze schwätzen.",
        "Я хочу учить французский, чтобы говорить с людьми в Люксембурге и во Франции."
      ]
    ]
  }
];
