// Generated by scripts/extract-seed-transport.mjs from Transport_Froen_Antwerten.md — do not hand-edit.
import type { SeedTopic } from "./seed-sproochen";

export const seedTopics: SeedTopic[] = [
  {
    "id": "transport",
    "name": "Transport",
    "cards": [
      [
        "Wat fir Transportmëttele ginn et zu Lëtzebuerg?",
        "Какие транспортные средства есть в Люксембурге?",
        "Zu Lëtzebuerg hu mir Bussen, Trammen, Autoen, Zich, Fliger, Taxi a Vëloen",
        "В Люксембурге есть автобусы, трамваи, машины, поезда, самолёты, такси и велосипеды."
      ],
      [
        "Wéi sidd Dir an de Sproochentest komm?",
        "Как Вы приехали на языковой тест?",
        "Ech si mam Auto komm",
        "Я приехала на машине."
      ],
      [
        "Wat fir een Auto hutt Dir?",
        "Какая у Вас машина?",
        "Ech hu Maserati",
        "У меня Maserati."
      ],
      [
        "Wéi ass Ären Auto?",
        "Какая Ваша машина?",
        "Ech hunn e groen, groussen Auto",
        "У меня большая серая машина."
      ],
      [
        "Ass dat e groussen oder e klengen Auto?",
        "Это большой или маленький автомобиль?",
        "Dat ass e groussen Auto",
        "Это большая машина."
      ],
      [
        "Hutt Dir e Bensinner, en Diesel oder en Elektroauto?",
        "У Вас машина на бензине, на дизеле или электрокар?",
        "Ech hunn e Bensinnerauto",
        "У меня машина на бензине."
      ],
      [
        "Wéi oft tankt Dir?",
        "Как часто Вы заправляетесь?",
        "Ech tanken zwee Mol de Mount",
        "Я заправляюсь дважды в месяц."
      ],
      [
        "Wou tankt Dir Ären Auto?",
        "Где Вы заправляете Вашу машину?",
        "Ech ginn op d'Q8 Tankstell",
        "Я заправляюсь на Q8."
      ],
      [
        "Wéi oft musst Dir Ären Auto oplueden?",
        "Как часто Вам нужно заряжать Вашу машину?",
        "dat ass relevant, well ech e Bensinnerauto hunn",
        "Не актуально, у меня бензиновая машина."
      ],
      [
        "Wou parkt Dir Ären Auto?",
        "Где Вы паркуетесь?",
        "Mir hunn eng Garage",
        "У нас есть гараж."
      ],
      [
        "Wéi laang hutt Der de Fürerschäin?",
        "Сколько лет у Вас водительские права?",
        "Ech hu mäi Fürerschäin fofzeng Joer.",
        "У меня права уже 15 лет."
      ],
      [
        "Wou hutt Dir Äre Führerschäin gemaach?",
        "Где Вы получили свои водительские права?",
        "Ech hunn mäi Führerschäin zu Sankt Petersburg gemaach",
        "Я получила права в Санкт-Петербурге."
      ],
      [
        "Wéi eng Transportmëttele benotzt Dir am dacksten?",
        "Какие транспортные средства Вы используете чаще всего?",
        "Ech benotzen am dacksten den Auto, de Bus an de Fliger",
        "Чаще всего я использую машину, автобус и самолёт."
      ],
      [
        "Wéi fuert Dir op d'Aarbecht?",
        "Как Вы едете на работу?",
        "Alisa: Ech fueren net op d'Aarbecht, well ech vun doheem schaffen. Alex: Ech fueren mam Auto oder mam Vëlo op d'Aarbecht.",
        "Alisa: Я не езжу на работу, потому что работаю из дома. Alex: Я езжу на работу на машине или на велосипеде."
      ],
      [
        "Wéi fannt Dir de Verkéier zu Lëtzebuerg?",
        "Как Вам дорожное движение в Люксембурге?",
        "Ech fannen de Verkéier zu Lëtzebuerg ganz gutt, et gi bal keng Stauen",
        "Я считаю, что движение в Люксембурге очень хорошее, пробок почти нет."
      ],
      [
        "Gëtt et vill Trafick an Ärer Uertschaft?",
        "В Вашем районе напряжённое движение?",
        "Nee, an der Stroossener Géigend ass wéineg Trafick",
        "Нет, в районе Штрассен трафик небольшой."
      ],
      [
        "Fueren d'Leit gutt zu Lëtzebuerg?",
        "В Люксембурге люди хорошо водят?",
        "Jo, d'Leit fueren gutt a respektéieren d'Reegelen",
        "Да, водят хорошо и соблюдают правила."
      ],
      [
        "Fueren d'Leit gutt an Ärem Land?",
        "В Вашей стране люди хорошо водят?",
        "Jo, d'Leit fueren och gutt a Russland",
        "Да, и в России тоже хорошо водят."
      ],
      [
        "Stitt Dir oft am Stau?",
        "Вы часто стоите в пробке?",
        "Nee, ech stinn net am Stau, well et zu Lëtzebuerg kaum Stauen ginn",
        "Нет, в пробках почти не стою."
      ],
      [
        "Wéi ass d'Situatioun mat Parkplazen an Ärer Géigend?",
        "Как с парковкой в вашем районе?",
        "Et ginn vill Parkplazen, och ënnerierdesch an op der Strooss",
        "Есть много парковок — и подземных, и на улице."
      ],
      [
        "Wou parkt Dir an der Stad?",
        "Где Вы паркуетесь в городе?",
        "Ech parken net an der Stad, well ech seelen dohi mam Auto fueren",
        "Я не паркуюсь в городе, так как редко туда езжу на машине."
      ],
      [
        "Kascht et vill, an der Stad ze parken?",
        "Парковка в городе дорогая?",
        "Jo, et kascht vill an der Stad ze parken",
        "Да, парковка в городе дорогая."
      ],
      [
        "Wéi fuert Dir akafen?",
        "Как Вы ездите за покупками?",
        "Ech fueren mam Auto akafen, meeschtens fiert mäi Mann",
        "Я езжу за покупками на машине, чаще едет мой муж."
      ],
      [
        "Wéi vill Zäit braucht Dir fir an de Supermarché?",
        "Сколько времени до супермаркета?",
        "Ech brauch ongeféier 10 Minutten",
        "Примерно 10 минут."
      ],
      [
        "Benotzt Dir oft den ëffentlechen Transport?",
        "Вы часто пользуетесь общественным транспортом?",
        "Jo, ech benotzen oft den ëffentlechen Transport, well en gratis a propper ass",
        "Да, часто, потому что он бесплатный и чистый."
      ],
      [
        "Gëtt et e Busarrêt no bei Ärem Haus?",
        "Рядом с домом есть остановка?",
        "Jo, e Busarrêt ass direkt vis-à-vis vu mengem Haus",
        "Да, прямо напротив моего дома."
      ],
      [
        "Wéi heescht dëse Busarrêt?",
        "Как называется остановка?",
        "Dëse Busarrêt heescht Barblé Quai 1",
        "Остановка называется Barblé Quai 1\\."
      ],
      [
        "Wéi eng Busser fueren do?",
        "Какие автобусы туда ходят?",
        "Do fueren d'Busser 8, 16 an 20",
        "Туда ходят автобусы 8, 16 и 20\\."
      ],
      [
        "Wéi oft kënnt e Bus?",
        "Как часто приходит автобус?",
        "De Bus kënnt all 5 Minutten",
        "Автобус приходит каждые 5 минут."
      ],
      [
        "Wéi fuert Dir an d'Vakanz?",
        "Как Вы ездите в отпуск?",
        "Ech fueren an d'Vakanz mam Fliger",
        "Я летаю в отпуск на самолёте."
      ],
      [
        "Flitt Dir oft mam Fliger?",
        "Вы часто летаете?",
        "Jo, ech fléien dacks, e puer Mol de Mount",
        "Да, я летаю часто, несколько раз в месяц."
      ],
      [
        "Flitt Dir vu Lëtzebuerg aus?",
        "Вы летаете из Люксембурга?",
        "Jo, ech fléien meeschtens vu Lëtzebuerg aus",
        "Да, чаще всего лечу из Люксембурга."
      ],
      [
        "Wéi fuert Dir op de Fluchhafen?",
        "Как Вы добираетесь в аэропорт?",
        "Ech fueren op de Fluchhafen mam Auto oder mam Bus 16",
        "Я добираюсь на машине или на автобусе 16\\."
      ],
      [
        "Mat wéi enger Fluchgesellschaft flitt Dir?",
        "Какими авиалиниями Вы летаете?",
        "Ech fléien meeschtens mat Luxair",
        "Чаще всего летаю с Luxair."
      ],
      [
        "Wou kaaft Dir Fluchbilljeeën?",
        "Где Вы покупаете авиабилеты?",
        "Ech kafen meng Fluchbilljeeën online",
        "Покупаю билеты онлайн."
      ],
      [
        "Sëtzt Dir léiwer bei der Fënster oder beim Gank?",
        "Вы предпочитаете сидеть у окна или у прохода?",
        "Ech sëtze léiwer beim Gank",
        "Предпочитаю сидеть у прохода."
      ],
      [
        "Kënnt Dir am Fliger schlofen?",
        "Вы можете спать в самолёте?",
        "Jo, ech kann iwwerall schlofen, och am Fliger",
        "Да, могу спать где угодно, даже в самолёте."
      ],
      [
        "Gëtt et en direkte Fluch an Äert Heemechtsland?",
        "Есть ли прямой рейс в вашу страну?",
        "Nee, ech muss am Moment zu Istanbul ëmklammen",
        "Нет, сейчас нужно делать пересадку в Стамбуле."
      ],
      [
        "Wéi vill kaschten d'Fluchticketen?",
        "Сколько стоят билеты?",
        "Si kaschten ongeféier 1000 Euro",
        "Они стоят примерно 1000 евро."
      ],
      [
        "Fuert Dir heiansdo mam Vëlo?",
        "Вы катаетесь на велосипеде?",
        "Jo, ech fueren am Summer mam Vëlo, ech hunn e schéine Vëlo",
        "Да, летом езжу на велосипеде, у меня красивый велик."
      ],
      [
        "Hutt Dir en eegene Vëlo?",
        "У Вас есть собственный велосипед?",
        "Jo, ech hunn mäin eegene Vëlo",
        "Да, у меня есть собственный велосипед."
      ],
      [
        "Benotzt Dir de Vél'oh, de Vëlosservice vun der Stad?",
        "Вы пользуетесь городским велосервисом Vél'oh?",
        "Nee, ech benotzen de Vél'oh net",
        "Нет, не пользуюсь."
      ],
      [
        "Ass e Vëlo fir Iech en Transportmëttel oder eng Sportaktivitéit?",
        "Велосипед — транспорт или спорт для Вас?",
        "Fir mech ass de Vëlo eng Aktivitéit",
        "Для меня это спорт/активность."
      ],
      [
        "Fuert Dir oft mam Zuch?",
        "Вы часто ездите на поезде?",
        "Jo, ech fueren dacks mam Zuch op Paräis",
        "Да, часто езжу поездом в Париж."
      ],
      [
        "Wuer sidd Dir déi leschte Kéier mam Zuch gefuer?",
        "Куда Вы последний раз ездили на поезде?",
        "Déi leschte Kéier sinn ech am leschte Mount op Paräis gefuer",
        "Последний раз ездила в Париж в прошлом месяце."
      ],
      [
        "Fuert Dir éischt oder zweet Klass?",
        "Вы ездите первым или вторым классом?",
        "Ech fueren heiansdo éischt, heiansdo zweet Klass",
        "Иногда первым, иногда вторым классом."
      ],
      [
        "Wat maacht Dir am Zuch iwwerem Fueren?",
        "Что Вы делаете в поезде?",
        "Am Zuch liesen ech oder ech schaffen",
        "Я читаю или работаю в поезде."
      ],
      [
        "Sidd Dir schonn eng Kéier mat der elektrescher Trottinett gefuer?",
        "Вы катались на электросамокате?",
        "Alisa: Nee, well dat ass geféierlech. Alex: Jo, ech hat eng eege Trottinett, mee elo net méi.",
        "Alisa: Нет, потому что это опасно. Alex: Да, у меня был свой самокат, но сейчас уже нет."
      ],
      [
        "An elo, fuert Dir net méi?",
        "А сейчас уже нет?",
        "Nee, well dat geféierlech ass",
        "Нет, потому что это опасно."
      ],
      [
        "Hutt Dir schonn eng Kéier de Carsharing benotzt?",
        "Вы пользовались каршерингом?",
        "Alisa: Nee, ech hunn nach ni de Carsharing benotzt. Alex: Jo, ech benotzen dacks de Carsharing zu Moskau.",
        "Alisa: Нет, я ни разу не пользовалась каршерингом. Alex: Да, я часто пользуюсь каршерингом в Москве."
      ],
      [
        "Wéini a wou hutt Dir Ären Auto kaaft?",
        "Когда и где Вы купили Вашу машину?",
        "Ech hu mäin Auto zu Lëtzebuerg kaaft.",
        "Я купила машину в Люксембурге."
      ],
      [
        "Wéi vill kascht dat, fir ze tanken?",
        "Сколько стоит заправка?",
        "Tanken kascht ee Euro fofzeg.",
        "Заправка стоит полтора евро."
      ],
      [
        "Ass et wäit ewech vun doheem op d'Aarbecht?",
        "Это далеко от дома до работы?",
        "Nee, et ass net wäit ewech.",
        "Нет, это недалеко."
      ],
      [
        "Wéi vill Zäit braucht Dir op d'Aarbecht?",
        "Сколько времени Вы добираетесь до работы?",
        "Ech brauche fofzéng Minutten op d'Aarbecht.",
        "Я добираюсь до работы за 15 минут."
      ],
      [
        "Wéini sidd Dir fir d'lescht mam Zuch gefuer?",
        "Когда Вы последний раз ездили на поезде?",
        "Ech si virun engem Mount mam Zuch op Paräis gefuer.",
        "Я ездила на поезде в Париж месяц назад."
      ],
      [
        "Wuer flitt Dir normalerweis?",
        "Куда Вы обычно летаете?",
        "Ech fléien dacks op London.",
        "Я часто летаю в Лондон."
      ],
      [
        "Gitt Dir oft zu Fouss?",
        "Вы часто ходите пешком?",
        "Jo, ech probéieren all Dag zu Fouss ze goen.",
        "Да, я стараюсь ходить пешком каждый день."
      ]
    ]
  }
];
