import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const SOURCE =
  process.argv[2] ?? path.join(os.homedir(), "Downloads", "sproochen-cards.html");

const html = fs.readFileSync(SOURCE, "utf8");

const match = html.match(/const TOPICS = (\[[\s\S]*?\n\]);/);
if (!match) {
  throw new Error(`Could not find "const TOPICS = [...]" in ${SOURCE}`);
}

// The matched text is a plain JS array/object literal (no imports, no
// function calls) copied out of a file we trust — safe to evaluate directly.
const topics = new Function(`"use strict"; return (${match[1]});`)();

const readyTopics = topics
  .filter((t) => t.ready)
  .map((t) => ({ id: t.id, name: t.name, cards: t.cards }));

const output = `// Generated by scripts/extract-seed.mjs from ${path.basename(SOURCE)} — do not hand-edit.
export type SeedCard = [questionLu: string, questionRu: string, answerLu: string, answerRu: string];
export type SeedTopic = { id: string; name: string; cards: SeedCard[] };

export const seedTopics: SeedTopic[] = ${JSON.stringify(readyTopics, null, 2)};
`;

const outPath = path.join(import.meta.dirname, "..", "data", "seed-sproochen.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, output);

const cardCount = readyTopics.reduce((n, t) => n + t.cards.length, 0);
console.log(
  `Wrote ${cardCount} card(s) across ${readyTopics.length} topic(s) to data/seed-sproochen.ts`
);
